### ISSUE TITLE
java.lang.SecurityException: Permission Denial: opening provider com.agilesoftresource.util.AndroZipProvider from ProcessRecord{457b8208 18990:at.tomtasche.reader/u0a10216} (pid=18990, uid=10216) that

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.droid#37]
java.lang.Exception: java.lang.SecurityException: Permission Denial: opening provider com.agilesoftresource.util.AndroZipProvider from ProcessRecord{457b8208 18990:at.tomtasche.reader/u0a10216} (pid=18990, uid=10216) that is not exported from uid 10203
at at.tomtasche.reader.ui.activity.MainActivity.onError(MainActivity.java:769)
at at.tomtasche.reader.ui.activity.DocumentActivity.handleError(DocumentActivity.java:248)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:155)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:1)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
at android.support.v4.content.Loader.deliverResult(Loader.java:103)
at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:221)
at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5328)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.agilesoftresource.util.AndroZipProvider from ProcessRecord{457b8208 18990:at.tomtasche.reader/u0a10216} (pid=18990, uid=10216) that is not exported from uid 10203
at android.os.Parcel.readException(Parcel.java:1425)
at android.os.Parcel.readException(Parcel.java:1379)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2822)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4668)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2379)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1104)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:711)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:617)
at android.content.ContentResolver.openInputStream(ContentResolver.java:452)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:138)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:1)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:240)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
java.lang.Exception: java.lang.SecurityException: Permission Denial: opening provider com.agilesoftresource.util.AndroZipProvider from ProcessRecord{457b8208 18990:at.tomtasche.reader/u0a10216} (pid=18990, uid=10216) that is not exported from uid 10203
at at.tomtasche.reader.ui.activity.MainActivity.onError(MainActivity.java:769)
at at.tomtasche.reader.ui.activity.DocumentActivity.handleError(DocumentActivity.java:248)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:155)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:1)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
at android.support.v4.content.Loader.deliverResult(Loader.java:103)
at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:221)
at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5328)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.agilesoftresource.util.AndroZipProvider from ProcessRecord{457b8208 18990:at.tomtasche.reader/u0a10216} (pid=18990, uid=10216) that is not exported from uid 10203
at android.os.Parcel.readException(Parcel.java:1425)
at android.os.Parcel.readException(Parcel.java:1379)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2822)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:4668)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2379)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1104)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:711)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:617)
at android.content.ContentResolver.openInputStream(ContentResolver.java:452)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:138)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:1)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:240)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)

**Comment by alexblack** [comment]
Did you ever figure anything out about this?  I'm getting something similar when users pick an image and try to crop it
