### ISSUE TITLE
libcore.io.ErrnoException: open failed: EISDIR (Is a directory)

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.droid#50]
java.lang.Exception: java.io.FileNotFoundException: /storage/sdcard0/Yahoo!/mail/attachments: open failed: EISDIR (Is a directory)
at at.tomtasche.reader.ui.activity.MainActivity.onError(MainActivity.java:769)
at at.tomtasche.reader.ui.activity.DocumentActivity.handleError(DocumentActivity.java:248)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:155)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:1)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.finishRetain(LoaderManager.java:298)
at android.support.v4.app.LoaderManagerImpl.finishRetain(LoaderManager.java:755)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:575)
at at.tomtasche.reader.ui.activity.MainActivity.onStart(MainActivity.java:258)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1230)
at android.app.Activity.performStart(Activity.java:5076)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4071)
at android.app.ActivityThread.access$700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5536)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.FileNotFoundException: /storage/sdcard0/Yahoo!/mail/attachments: open failed: EISDIR (Is a directory)
at libcore.io.IoBridge.open(IoBridge.java:416)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at java.io.FileInputStream.<init>(FileInputStream.java:105)
at android.content.ContentResolver.openInputStream(ContentResolver.java:455)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:138)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:1)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:240)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: libcore.io.ErrnoException: open failed: EISDIR (Is a directory)
at libcore.io.IoBridge.open(IoBridge.java:405)
... 14 more
java.lang.Exception: java.io.FileNotFoundException: /storage/sdcard0/Yahoo!/mail/attachments: open failed: EISDIR (Is a directory)
at at.tomtasche.reader.ui.activity.MainActivity.onError(MainActivity.java:769)
at at.tomtasche.reader.ui.activity.DocumentActivity.handleError(DocumentActivity.java:248)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:155)
at at.tomtasche.reader.ui.activity.DocumentActivity.onLoadFinished(DocumentActivity.java:1)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.finishRetain(LoaderManager.java:298)
at android.support.v4.app.LoaderManagerImpl.finishRetain(LoaderManager.java:755)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:575)
at at.tomtasche.reader.ui.activity.MainActivity.onStart(MainActivity.java:258)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1230)
at android.app.Activity.performStart(Activity.java:5076)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4071)
at android.app.ActivityThread.access$700(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5536)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.FileNotFoundException: /storage/sdcard0/Yahoo!/mail/attachments: open failed: EISDIR (Is a directory)
at libcore.io.IoBridge.open(IoBridge.java:416)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at java.io.FileInputStream.<init>(FileInputStream.java:105)
at android.content.ContentResolver.openInputStream(ContentResolver.java:455)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:138)
at at.tomtasche.reader.background.DocumentLoader.loadInBackground(DocumentLoader.java:1)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:240)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: libcore.io.ErrnoException: open failed: EISDIR (Is a directory)
at libcore.io.IoBridge.open(IoBridge.java:405)
... 14 more

**Comment by chenhua1008611** [comment]
我也碰到了类似的问题 ，这个需要一级级创建目录，例如这样
  File appDir = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "logopic");
        if (!appDir.exists()) {
            appDir.mkdir();
        }
        //文件夹上创建文件
        File file = new File(appDir, "logo.png");

**Comment by chenhua1008611** [comment]
我也碰到了类似的问题 ，这个需要一级级创建目录，例如这样
File appDir = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "logopic");
if (!appDir.exists()) {
appDir.mkdir();
}
//文件夹上创建文件
File file = new File(appDir, "logo.png");
亲测可以

**Comment by brahmyadigopula** [comment]
Same error but this issue is coming in the android Q especially. @chenhua1008611  @TomTasche

**Comment by TomTasche** [comment]
> Same error but this issue is coming in the android Q especially. @chenhua1008611 @TomTasche

Could you share a way to reliably reproduce this issue? I'm not able to reproduce it unfortunately.
